version: "3.9"

services:

  grafana:
    image: grafana/grafana-oss:9.3.6
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-clock-panel,grafana-simple-json-datasource"

  ping:
    image: prom/blackbox-exporter:v0.23.0
    tty: true
    stdin_open: true
    volumes:
      - "./blackbox/config:/config"
    command:
      - '--config.file=/config/blackbox.yml'

  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - "./prometheus/:/etc/prometheus/"
      - "prometheus_data:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  speedtest:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter:v3.5.3

  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "./traefik/configuration.toml:/configuration/configuration.toml:ro"

volumes:
  prometheus_data: { }
  grafana_data: { }
