name: Verify

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install EditorConfig Checker
        run: pip install editorconfig-checker
      - name: Check EditorConfig
        run: editorconfig-checker .
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .
      - uses: bewuethr/shellcheck-action@v2
